version: 2.1

jobs:
  deploy:
    machine:
      enabled: true
    working_directory: ~/python_microservice_ampq_aws-sms
    steps:
      - add_ssh_keys:
          fingerprints:
            - "0c:33:a8:8c:40:06:fa:ae:13:c8:63:a6:e7:52:a1:b0"
      - checkout
      - run:
          name: Perform ports mapping and setting environment
          command: |
              chmod +x ./mapping_docker_env.sh && ./mapping_docker_env.sh
              cat .app/.env
      

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
