FROM python:3.7
WORKDIR /app
RUN apt-get update && apt-get install --assume-yes apt-utils
RUN apt-get install -y gcc musl-dev nano
COPY ./requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY ./app .
CMD ["python", "service.py"]
